blank_issues_enabled: false
contact_links:
    - name: Support Discord
      url: https://discord.gg/M7dm4Kg6HN
      about: Please ask and answer questions here.
    - name: New Task Template
      url: https://github.com/TheRealHeyJack/Temp/issues/new?template=TASK_TEMPLATE.md
      about: Submit a new task.
